# Default compile flags.
CFLAGS=-Os -g

# Kernel path
RAVENSCAR_SRC=/home/user/Desktop/gnatmindstorms2011/lib/gcc/arm-eabi/4.5.3/rts-ravenscar-sfp/ravenscar

# Main subprogram.
PRG=remote

# Main targets from Makefile.inc (for GPS)
all:

clean:

include $(RAVENSCAR_SRC)/Makefile.inc
